baseURL = 'https://geocuvar.pages.dev/'
locale = 'en-US'
title = 'GEOCUVAR'

[taxonomies]
  tag = 'tags'

[menus]
  [[menus.footer]]
    name = 'About'
    pageRef = '/about'
    weight = 10

[services]
  [services.rss]
    limit = 90
