baseURL = 'https://geocuvar.pages.dev/'
languageCode = 'en-us'
title = 'GEOCUVAR'

[menus]
  [[menus.footer]]
    name = 'About'
    pageRef = '/about'
    weight = 10

[services]
  [services.rss]
    limit = 45
